/**
 * Verity report renderer — JSON + Markdown output.
 */

import { VerityReport, CriterionResult } from "./types.js";

// ---------------------------------------------------------------------------
// JSON
// ---------------------------------------------------------------------------

export function renderJson(report: VerityReport): string {
  return JSON.stringify(report, null, 2);
}

// ---------------------------------------------------------------------------
// Markdown
// ---------------------------------------------------------------------------

const STATUS_BADGE: Record<string, string> = {
  VERIFIED: "✅ VERIFIED",
  FAILED: "❌ FAILED",
  UNCERTAIN: "⚠️  UNCERTAIN",
};

function renderResult(r: CriterionResult): string {
  const badge = STATUS_BADGE[r.status] ?? r.status;
  const lines: string[] = [];

  lines.push(`### ${r.id} — ${badge}`);
  lines.push("");
  lines.push(`**Criterion:** ${r.text}`);
  lines.push("");
  lines.push(`**Reason:** ${r.reason}`);
  lines.push("");

  if (r.evidence.length > 0) {
    lines.push("**Evidence:**");
    lines.push("");
    for (const e of r.evidence) {
      lines.push(`- **${e.description}**`);
      if (e.filePath) lines.push(`  - File: \`${e.filePath}\``);
      if (e.snippet) {
        // Indent multi-line snippets as a code block.
        const isMultiLine = e.snippet.includes("\n");
        if (isMultiLine) {
          lines.push("  ```");
          for (const sl of e.snippet.split("\n")) {
            lines.push(`  ${sl}`);
          }
          lines.push("  ```");
        } else {
          lines.push(`  - \`${e.snippet}\``);
        }
      }
    }
  }

  return lines.join("\n");
}

export function renderMarkdown(report: VerityReport): string {
  const { summary, results, generatedAt, specFile } = report;
  const lines: string[] = [];

  lines.push("# Verity — Verification Report");
  lines.push("");
  lines.push(`**Spec:** \`${specFile}\``);
  lines.push(`**Generated:** ${generatedAt}`);
  lines.push("");

  lines.push("## Summary");
  lines.push("");
  lines.push(
    `| Total | ✅ Verified | ❌ Failed | ⚠️  Uncertain |`
  );
  lines.push(`|-------|------------|----------|--------------|`);
  lines.push(
    `| ${summary.total} | ${summary.verified} | ${summary.failed} | ${summary.uncertain} |`
  );
  lines.push("");

  lines.push("## Results");
  lines.push("");
  for (const r of results) {
    lines.push(renderResult(r));
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  lines.push("*Generated by [Verity](./verity/run.ts)*");

  return lines.join("\n");
}
